// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package middleware

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Address struct {
	Street       string  `json:"street"`
	Number       string  `json:"number"`
	Complement   *string `json:"complement,omitempty"`
	Neighborhood string  `json:"neighborhood"`
	City         string  `json:"city"`
	State        string  `json:"state"`
	ZipCode      string  `json:"zipCode"`
	Country      string  `json:"country"`
}

type AddressInput struct {
	Street       string  `json:"street"`
	Number       string  `json:"number"`
	Complement   *string `json:"complement,omitempty"`
	Neighborhood string  `json:"neighborhood"`
	City         string  `json:"city"`
	State        string  `json:"state"`
	ZipCode      string  `json:"zipCode"`
	Country      string  `json:"country"`
}

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type CreateProductInput struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Category    ProductCategory `json:"category"`
	Price       float64         `json:"price"`
	Stock       int             `json:"stock"`
	ThcContent  *float64        `json:"thcContent,omitempty"`
	CbdContent  *float64        `json:"cbdContent,omitempty"`
	Strain      *string         `json:"strain,omitempty"`
	Origin      *string         `json:"origin,omitempty"`
	ImageURLs   []string        `json:"imageURLs"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Order struct {
	ID                 string       `json:"id"`
	Buyer              *User        `json:"buyer"`
	Items              []*OrderItem `json:"items"`
	TotalAmount        float64      `json:"totalAmount"`
	Status             OrderStatus  `json:"status"`
	ShippingAddress    *Address     `json:"shippingAddress"`
	TemporalWorkflowID string       `json:"temporalWorkflowID"`
	PaymentIntentID    *string      `json:"paymentIntentID,omitempty"`
	CreatedAt          time.Time    `json:"createdAt"`
	UpdatedAt          time.Time    `json:"updatedAt"`
}

type OrderItem struct {
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	UnitPrice float64  `json:"unitPrice"`
	Subtotal  float64  `json:"subtotal"`
}

type OrderItemInput struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PlaceOrderInput struct {
	Items           []*OrderItemInput `json:"items"`
	ShippingAddress *AddressInput     `json:"shippingAddress"`
}

type Product struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Category    ProductCategory `json:"category"`
	Price       float64         `json:"price"`
	Stock       int             `json:"stock"`
	ThcContent  *float64        `json:"thcContent,omitempty"`
	CbdContent  *float64        `json:"cbdContent,omitempty"`
	Strain      *string         `json:"strain,omitempty"`
	Origin      *string         `json:"origin,omitempty"`
	ImageURLs   []string        `json:"imageURLs"`
	Seller      *User           `json:"seller"`
	IsActive    bool            `json:"isActive"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type ProductConnection struct {
	Edges      []*ProductEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type ProductEdge struct {
	Node   *Product `json:"node"`
	Cursor string   `json:"cursor"`
}

type ProductFilterInput struct {
	Category *ProductCategory `json:"category,omitempty"`
	MinPrice *float64         `json:"minPrice,omitempty"`
	MaxPrice *float64         `json:"maxPrice,omitempty"`
	MinThc   *float64         `json:"minThc,omitempty"`
	MaxThc   *float64         `json:"maxThc,omitempty"`
	Search   *string          `json:"search,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type UpdateProductInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Stock       *int     `json:"stock,omitempty"`
	ThcContent  *float64 `json:"thcContent,omitempty"`
	CbdContent  *float64 `json:"cbdContent,omitempty"`
	Strain      *string  `json:"strain,omitempty"`
	Origin      *string  `json:"origin,omitempty"`
	ImageURLs   []string `json:"imageURLs,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Role      UserRole  `json:"role"`
	Address   *Address  `json:"address,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type OrderStatus string

const (
	OrderStatusPending           OrderStatus = "PENDING"
	OrderStatusPaymentProcessing OrderStatus = "PAYMENT_PROCESSING"
	OrderStatusPaymentConfirmed  OrderStatus = "PAYMENT_CONFIRMED"
	OrderStatusPreparing         OrderStatus = "PREPARING"
	OrderStatusShipped           OrderStatus = "SHIPPED"
	OrderStatusDelivered         OrderStatus = "DELIVERED"
	OrderStatusCancelled         OrderStatus = "CANCELLED"
	OrderStatusRefunded          OrderStatus = "REFUNDED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusPaymentProcessing,
	OrderStatusPaymentConfirmed,
	OrderStatusPreparing,
	OrderStatusShipped,
	OrderStatusDelivered,
	OrderStatusCancelled,
	OrderStatusRefunded,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusPending, OrderStatusPaymentProcessing, OrderStatusPaymentConfirmed, OrderStatusPreparing, OrderStatusShipped, OrderStatusDelivered, OrderStatusCancelled, OrderStatusRefunded:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProductCategory string

const (
	ProductCategoryFlower     ProductCategory = "FLOWER"
	ProductCategoryOil        ProductCategory = "OIL"
	ProductCategoryEdible     ProductCategory = "EDIBLE"
	ProductCategoryExtraction ProductCategory = "EXTRACTION"
)

var AllProductCategory = []ProductCategory{
	ProductCategoryFlower,
	ProductCategoryOil,
	ProductCategoryEdible,
	ProductCategoryExtraction,
}

func (e ProductCategory) IsValid() bool {
	switch e {
	case ProductCategoryFlower, ProductCategoryOil, ProductCategoryEdible, ProductCategoryExtraction:
		return true
	}
	return false
}

func (e ProductCategory) String() string {
	return string(e)
}

func (e *ProductCategory) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductCategory", str)
	}
	return nil
}

func (e ProductCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserRole string

const (
	UserRoleCustomer UserRole = "CUSTOMER"
	UserRoleSeller   UserRole = "SELLER"
	UserRoleAdmin    UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleCustomer,
	UserRoleSeller,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleCustomer, UserRoleSeller, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
